{
 "title": "INITITIATION",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{instance=\"localhost:9100\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "RAM Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(sum by (cpu)(irate(node_cpu_seconds_total{mode!=\"idle\"}[5m:15s])))*100\n"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes - node_memory_MemFree_bytes) / (node_memory_MemTotal_bytes)) * 100"
    }
   ]
  },
  {
   "title": "FS Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) ((node_filesystem_size_bytes - node_filesystem_avail_bytes) / node_filesystem_size_bytes)* 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Metrics Basics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total[5m])",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Info RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "TOTAL" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes",
     "legendFormat": "USED"
    }
   ]
  },
  {
   "title": "FileSystems",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (device,mountpoint)(node_filesystem_size_bytes)",
     "legendFormat": "TOTAL-{{device}}-{{mountpoint}}"
    },
    {
     "expr": "sum by (device,mountpoint)(node_filesystem_size_bytes - node_filesystem_avail_bytes)",
     "legendFormat": "USED-{{device}}-{{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,cpu)(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100",
     "legendFormat": "IDLE - {{instance}} - {{cpu}}"
    },
    {
     "expr": "sum by (instance,cpu)(irate(node_cpu_seconds_total{mode=\"iowait\"}[5m])) * 100",
     "legendFormat": "IOWAIT - {{instance}} - {{cpu}}"
    },
    {
     "expr": "sum by (instance,cpu)(irate(node_cpu_seconds_total{mode=\"user\"}[5m])) * 100",
     "legendFormat": "USER - {{instance}} - {{cpu}}"
    }
   ]
  }
 ]
}